---
- name: Create EC@ instance
  hosts: localhost
  
  tasks:

    - name: Launch an EC2 Instance

      amazon.aws.ec2_instance:

        name: "Test-Ansible"

        key_name: "{{ key_name }}"

        #aws_access_key: "{{ aws_access_key }}"

        #aws_secret_key: "{{ aws_secret_key }}"

        vpc_subnet_id: "{{ subnet.subnet.id }}"

        instance_type: "{{ instance_type }}"

        security_group: "{{ sec_group  }}"

        count: 1

        wait: yes

        aws_region: "{{ region }}"

        network:

          assign_public_ip: true

        image_id: "{{ ami }}"
